name: Deploy Application

on:
  push:
    branches:
      - develop

jobs:
  create-deployment-artifacts:
    name: Communicate Develop Pipline

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: communicate
          MYSQL_USER: communicate
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer Install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate Key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mysql -uroot -hmysql -proot -e 'CREATE DATABASE IF NOT EXISTS communicate;'
      - name: Create Tables
        run: php artisan migrate
